version: '3.6'
services:
  postgres:
    image: postgres:14.1
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphile:
    image: graphile/postgraphile:4
    ports:
      - "5000:5000"
    depends_on:
    - "postgres"
    restart: always
    init: true
    volumes:
      - "./:/app"
    command: --connection postgres://postgres:postgrespassword@postgres:5432/postgres\?sslmode=disable --enhance-graphiql --schema public --watch --allow-explain --export-schema-graphql /app/schema.graphql
volumes:
  db_data:
    driver: local