package dal

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// UUIDNsURL calls the stored function 'public.uuid_ns_url() uuid' on db.
func UUIDNsURL(ctx context.Context, db DB) (uuid.UUID, error) {
	// call public.uuid_ns_url
	const sqlstr = `SELECT * FROM public.uuid_ns_url()`
	// run
	var r0 uuid.UUID
	logf(sqlstr)
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&r0); err != nil {
		return uuid.UUID{}, logerror(err)
	}
	return r0, nil
}
