package dal

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// UUIDGenerateV5 calls the stored function 'public.uuid_generate_v5(uuid, text) uuid' on db.
func UUIDGenerateV5(ctx context.Context, db DB, namespace uuid.UUID, name string) (uuid.UUID, error) {
	// call public.uuid_generate_v5
	const sqlstr = `SELECT * FROM public.uuid_generate_v5($1, $2)`
	// run
	var r0 uuid.UUID
	logf(sqlstr, namespace, name)
	if err := db.QueryRowContext(ctx, sqlstr, namespace, name).Scan(&r0); err != nil {
		return uuid.UUID{}, logerror(err)
	}
	return r0, nil
}
