app_name: "Bizbuzim Development"
host_port: 0.0.0.0:8080
web_ui: true
log_level: "info"
log_format: "plain"
http_compress: true
server_timing: true
production: false
auth_fail_block: false
enable_tracing: true
reload_on_config_change: true
cors_allowed_origins: ["*"]
cors_allowed_headers: []
cors_debug: false
subs_poll_every_seconds: 5
default_limit: 20
debug: false
hot_deploy: false
admin_secret_key: bizbuzim
database:
  dbname: postgres
  port: 5432
  ping_timeout: 1m
  enable_tls: false