baseURL: https://docs.bizbuzim.info
title: "Bizbuzim"
theme: "hugo-theme-learn"
outputs:
  home: ["HTML", "JSON", "RSS"]
params:
  editURL: http://github.com/bizbuzim/bizbuzim/docs/
  disableNextPrev: true
  themeVariant: "green"
