name: ci

on:  
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: ci
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd web && yarn
    - name: Run tests
      run: cd web && yarn test:ci