name: release

on: [workflow_dispatch]

jobs:
  postgraphile:
    name: postgraphile
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Push
      run: |
        docker build -t $(cat docker-repository.txt)/postgraphile -f graphile/Dockerfile .
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push $(cat docker-repository.txt)/postgraphile
    - name: Update Cloud run
      run: gcloud run services update postgraphile --region us-central1 --image $(cat docker-repository.txt)/postgraphile