name: migration

on:
  push:
    paths:
      - db/**
      - .github/workflows/migration.yaml
      - cmd/tools/migration/**
      - pkg
jobs:
  migration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: false
          tags: bizbuzim/migrate:latest
          file: cmd/tools/Dockerfile
          load: true
      - run: |
          docker run -v "/var/run/docker.sock:/var/run/docker.sock:rw" --network=host -v $(pwd)/db:/app/db -v $(pwd)/pkg:/app/pkg  bizbuzim/migrate sync
          git diff --exit-code
      - if: ${{ github.ref == 'ref/heads/main' }} 
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - if: ${{ github.ref == 'ref/heads/main' }} 
        run: |
          gcloud sql connect bizbuzim-production &
          docker run -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST_PRODUCTION }} -e POSTGRES_PASSWORD=${{ secrets.PGPASSWORD_PRODUCTION }} bizbuzim/migrate sync --production
